import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def generate_pdf_report(patient, audiogram, analysis):
    """
    Generates an AI Clinical Report PDF.

    Returns:
        Absolute path of generated PDF.
    """

    reports_folder = "reports"
    os.makedirs(reports_folder, exist_ok=True)

    filename = (
        f"report_patient_{patient.id}_"
        f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    )

    filepath = os.path.join(reports_folder, filename)

    doc = SimpleDocTemplate(filepath)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    story = []

    story.append(Paragraph("HearSense AI", title_style))
    story.append(
        Paragraph(
            "AI Clinical Decision Support Report",
            styles["Heading2"],
        )
    )

    story.append(Spacer(1, 20))

    patient_table = Table(
        [
            ["Patient ID", patient.id],
            ["Name", patient.name],
            ["Age", patient.age],
            ["Gender", patient.gender],
            ["Phone", patient.phone],
            ["Email", patient.email],
            ["Test Date", str(audiogram.test_date)],
        ],
        colWidths=[160, 300],
    )

    patient_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )

    story.append(patient_table)

    story.append(Spacer(1, 20))

    analysis_table = Table(
        [
            ["Right PTA", analysis["right_pta"]],
            ["Left PTA", analysis["left_pta"]],
            ["Right Degree", analysis["right_degree"]],
            ["Left Degree", analysis["left_degree"]],
            ["Hearing Loss Type", analysis["hearing_loss_type"]],
            ["Disability %", analysis["disability_percentage"]],
        ],
        colWidths=[160, 300],
    )

    analysis_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )

    story.append(analysis_table)

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>AI Clinical Summary</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            analysis["clinical_summary"],
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Recommendations</b>",
            styles["Heading2"],
        )
    )

    for recommendation in analysis["recommendations"]:
        story.append(
            Paragraph(
                f"• {recommendation}",
                styles["BodyText"],
            )
        )

    story.append(Spacer(1, 40))

    story.append(
        Paragraph(
            f"Generated on: {datetime.now()}",
            styles["BodyText"],
        )
    )

    story.append(
        Paragraph(
            "Generated by HearSense AI",
            styles["BodyText"],
        )
    )

    doc.build(story)

    return filepath